#!/bin/bash

# Script to demonstrate CPU/Memory scaling with VUs
# This shows how to properly stress test to see resource usage

echo "════════════════════════════════════════════════════════════════"
echo "  CPU/Memory Stress Test Configuration Guide"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Check if running from oracle directory
if [ ! -f "docker-compose.yml" ]; then
    echo "❌ Error: Please run this script from the oracle/ directory"
    exit 1
fi

echo "Why Your CPU/Memory Isn't Spiking:"
echo "-----------------------------------"
echo "• Current POOL_MAX: 200 connections"
echo "• Stress test VUs: 1000 users"
echo "• Result: 66% requests timeout in queue (don't execute)"
echo "• Only 33% execute → Only ~330 concurrent operations"
echo "• Database I/O operations don't use much CPU"
echo ""
echo "To See CPU/Memory Scale with VUs:"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  OPTION 1: Scale Connection Pool (RECOMMENDED)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "This allows more requests to actually execute concurrently."
echo ""
echo "Run stress test with scaled pool:"
echo ""
echo "  export POOL_MAX=1000"
echo "  export POOL_MIN=200"
echo "  export QUEUE_TIMEOUT=60000"
echo "  docker-compose down"
echo "  docker-compose up -d oracle-test-app"
echo "  docker-compose up k6"
echo ""
echo "Expected Results:"
echo "  • More requests execute (instead of timeout)"
echo "  • CPU usage increases (more concurrent DB operations)"
echo "  • Memory usage increases (more connection buffers)"
echo "  • May hit Oracle DB limits instead of app limits"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  OPTION 2: Quick Test (Using .env.stress file)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Update .env.stress with your database credentials"
echo "2. Run:"
echo ""
echo "  docker-compose down"
echo "  docker-compose --env-file .env.stress up"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  OPTION 3: Check Database Session Limits First"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Before increasing POOL_MAX to 1000, verify Oracle can handle it:"
echo ""
echo "  docker-compose up -d oracle-test-app"
echo "  docker exec -it oracle-test-app node -e \""
echo "    const oracledb = require('oracledb');"
echo "    oracledb.getConnection({"
echo "      user: process.env.ORACLE_USER,"
echo "      password: process.env.ORACLE_PASSWORD,"
echo "      connectString: process.env.ORACLE_CONNECT_STRING"
echo "    }).then(conn => {"
echo "      return conn.execute("
echo "        'SELECT name, value FROM v\\\$parameter WHERE name IN (\\\'processes\\\', \\\'sessions\\\')'"
echo "      ).then(result => {"
echo "        console.log('Database Limits:');"
echo "        result.rows.forEach(row => console.log(\\\`  \\\${row[0]}: \\\${row[1]}\\\`));"
echo "        return conn.close();"
echo "      });"
echo "    }).catch(e => console.error('Error:', e.message));"
echo "  \""
echo ""
echo "Common Oracle limits:"
echo "  • processes: 150-300 (typical)"
echo "  • sessions: 172-472 (typically processes * 1.1 + 5)"
echo ""
echo "If limit is too low, contact your Oracle DBA to increase."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  Understanding Resource Usage"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Database operations are I/O-bound, not CPU-bound:"
echo ""
echo "  Request → App (low CPU) → Wait for DB → Response"
echo "                              ↑"
echo "                         I/O wait (no CPU)"
echo ""
echo "To see CPU spike, you need:"
echo "  1. More concurrent operations (increase POOL_MAX)"
echo "  2. OR CPU-intensive operations (data processing)"
echo ""
echo "Memory increases with:"
echo "  • More active connections (each uses ~1-2MB)"
echo "  • More result set buffering"
echo "  • More OpenTelemetry spans in memory"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  Expected Resource Usage at Different Pool Sizes"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "POOL_MAX=200 (current):"
echo "  • Max concurrent operations: ~200"
echo "  • Expected CPU: 5-15% (I/O wait)"
echo "  • Expected Memory: 200-400MB"
echo "  • 1000 VUs result: 66% timeout"
echo ""
echo "POOL_MAX=500:"
echo "  • Max concurrent operations: ~500"
echo "  • Expected CPU: 15-40%"
echo "  • Expected Memory: 500-800MB"
echo "  • 1000 VUs result: 30-40% timeout"
echo ""
echo "POOL_MAX=1000:"
echo "  • Max concurrent operations: ~1000"
echo "  • Expected CPU: 40-80%"
echo "  • Expected Memory: 1-2GB"
echo "  • 1000 VUs result: <10% timeout"
echo "  • May hit Oracle DB limits"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "  Quick Start Commands"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Test with 500 connections (moderate scaling):"
echo "  export POOL_MAX=500 && docker-compose down && docker-compose up"
echo ""
echo "Test with 1000 connections (full scaling):"
echo "  export POOL_MAX=1000 && docker-compose down && docker-compose up"
echo ""
echo "Monitor resources during test:"
echo "  docker stats oracle-test-app"
echo ""
echo "Check connection pool usage:"
echo "  docker logs oracle-test-app | grep -i 'pool\\|connection'"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo ""

# Offer to run the test
read -p "Do you want to run stress test with POOL_MAX=1000? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo "Starting stress test with POOL_MAX=1000..."
    echo ""
    export POOL_MAX=1000
    export POOL_MIN=200
    export QUEUE_TIMEOUT=60000
    export TEST_INTENSITY=stress
    docker-compose down
    echo ""
    echo "Starting containers..."
    docker-compose up -d oracle-test-app
    sleep 10
    echo ""
    echo "Application started. Monitor with:"
    echo "  docker stats oracle-test-app"
    echo ""
    echo "Starting K6 load test..."
    docker-compose up k6
else
    echo ""
    echo "Test not started. Use the commands above when ready."
fi
